services:
  httpd_website:
    container_name: httpd_website
    restart: unless-stopped
    image: httpd
    expose:
      - 80
  nginx_website:
    container_name: nginx_website
    restart: unless-stopped
    image: nginx:alpine
    expose:
      - 80
  kong_db:
    container_name: kong_db
    restart: unless-stopped
    image: postgres
    environment:
      - POSTGRES_PASSWORD=kong_pass
      - POSTGRES_USER=kong_user
      - POSTGRES_DB=kong
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kong_db:/var/lib/postgresql
  kong_db_migration:
    container_name: kong_db_migration
    image: kong/kong-gateway:2.8.1.4-alpine
    command: [ "kong", "migrations", "bootstrap" ]
    depends_on:
      kong_db:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_db
      - KONG_PG_PASSWORD=kong_pass
      - KONG_PG_USER=kong_user
  kong:
    container_name: kong
    restart: unless-stopped
    depends_on:
      kong_db_migration:
        condition: service_completed_successfully
    image: kong/kong-gateway:2.8.1.4-alpine
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_db
      - KONG_PG_USER=kong_user
      - KONG_PG_PASSWORD=kong_pass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PORTAL=on
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 10
  deck:
    container_name: deck
    image: kong/deck
    depends_on:
      kong:
        condition: service_healthy
    command: "sync -s ./declarative/kong.yml --kong-addr http://kong:8001"
    volumes:
      - ./declarative:/declarative
volumes:
  kong_db: null
networks:
  default:
    external:
      name: api_gateway
