services:
  httpd_website:
    container_name: httpd_website
    restart: unless-stopped
    image: httpd
    expose:
      - 80

  nginx_website:
    container_name: nginx_website
    restart: unless-stopped
    image: nginx:alpine
    expose:
      - 80

  kong_gateway:
    container_name: kong_gateway
    restart: unless-stopped
    image: kong/kong-gateway:2.8.1.4-alpine
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PORTAL=on
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
      - ./declarative:/kong/declarative

networks:
  default:
    external:
      name: api_gateway